give better error when cannot import a testname
fix #259

Currently, when a testname cannot be imported, an AttributeError is
raised, and no stacktrace is displayed. This is imprecise becaues this
AttributeError can be caused by an "import" error which stacktrace gives
useful information to the user about the reasons of the failure.

Let consider the following example:

    .
    ├── a_module.py
    └── a_subpackage
        ├── __init__.py
        └── test_foo.py

a_module.py is empty, and test_foo.py contains this code:

    raise ImportError('BOOM !')

The current behaviour:

    $ nose2 a_module.test_dont_exist
    E
    ===============================================================
    ERROR: a_module.test_dont_exist (nose2.loader.LoadTestsFailure)
    ---------------------------------------------------------------
    AttributeError: 'module' object has no attribute 'test_dont_exist'

    ---------------------------------------------------------------
    Ran 1 test in 0.000s

    FAILED (errors=1)

    $ nose2 a_pkg.test_foo

    E
    ===============================================================
    ERROR: a_pkg.test_foo (nose2.loader.LoadTestsFailure)
    ---------------------------------------------------------------
    AttributeError: 'module' object has no attribute 'test_foo'

    ---------------------------------------------------------------
    Ran 1 test in 0.000s

    FAILED (errors=1)

The first error is all right but in the second case it is clearly
misleading.  The actual error comes from the fact that `a_pkg.test_foo`
raises an `ImportError`, but this is swallowed by nose2.

The new behaviour:

    $ nose2 a_module.test_dont_exist
    E
    ===============================================================
    ERROR: a_module.test_dont_exist (nose2.loader.LoadTestsFailure)
    ---------------------------------------------------------------
    AttributeError: '<module 'a_module' from './a_module.pyc'>' \
        has not attribute 'test_dont_exist'

    Maybe caused by

    Traceback (most recent call last):

      File "./nose2/nose2/util.py", line 180, in try_import_module_from_name
        module = __import__('.'.join(splitted_name))

    ImportError: No module named test_dont_exist

    ---------------------------------------------------------------
    Ran 1 test in 0.000s

    FAILED (errors=1)

    $ nose2 a_module.test_foo
    E
    ===============================================================
    ERROR: a_pkg.test_foo (nose2.loader.LoadTestsFailure)
    ---------------------------------------------------------------
    AttributeError: \
        '<module 'a_pkg' from './nose2/a_pkg/__init__.pyc'>' has \
        no attribute 'test_foo'

    Maybe caused by

    Traceback (most recent call last):

      File "./nose2/util.py", line 180, in try_import_module_from_name
        module = __import__('.'.join(splitted_name))

      File "./nose2/a_pkg/test_foo.py", line 1, in <module>
        raise ImportError('BOOM !')

    ImportError: BOOM !

    ---------------------------------------------------------------
    Ran 1 test in 0.000s

    FAILED (errors=1)

In both case we print the `ImportError`. In the first case, it's
irrelevant and just add noise to the output, but we still have the
relevant `AttributeError`.  In the second case however, we now have the
actual `ImportError`.

To sum up, this change makes the output a little bit noisier, but
provides much needed info about the failures in some cases.